//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowonderPhone.Languish {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WowonderPhone.Languish.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone.
        /// </summary>
        internal static string Everyone {
            get {
                return ResourceManager.GetString("Everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From your phone contacts.
        /// </summary>
        internal static string FN_FromPhoneContact {
            get {
                return ResourceManager.GetString("FN_FromPhoneContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No contacts available.
        /// </summary>
        internal static string FN_NoContactPhoneAreAvailble {
            get {
                return ResourceManager.GetString("FN_NoContactPhoneAreAvailble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No friends available.
        /// </summary>
        internal static string FN_NoUsersAreAvailble {
            get {
                return ResourceManager.GetString("FN_NoUsersAreAvailble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts List.
        /// </summary>
        internal static string FN_OfflineContacts {
            get {
                return ResourceManager.GetString("FN_OfflineContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Users.
        /// </summary>
        internal static string FN_OnlineContacts {
            get {
                return ResourceManager.GetString("FN_OnlineContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People you may know.
        /// </summary>
        internal static string FN_PeopleYoumayKnow {
            get {
                return ResourceManager.GetString("FN_PeopleYoumayKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Label_About {
            get {
                return ResourceManager.GetString("Label_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        internal static string Label_About_Me {
            get {
                return ResourceManager.GetString("Label_About_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Label_Accept_Terms {
            get {
                return ResourceManager.GetString("Label_Accept_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Label_Account {
            get {
                return ResourceManager.GetString("Label_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Label_Add {
            get {
                return ResourceManager.GetString("Label_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a photo..
        /// </summary>
        internal static string Label_Add_a_Photo {
            get {
                return ResourceManager.GetString("Label_Add_a_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add All / Next.
        /// </summary>
        internal static string Label_Add_All_And_Next {
            get {
                return ResourceManager.GetString("Label_Add_All_And_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add friend.
        /// </summary>
        internal static string Label_AddFriend {
            get {
                return ResourceManager.GetString("Label_AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Label_All {
            get {
                return ResourceManager.GetString("Label_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already a user? Login now.
        /// </summary>
        internal static string Label_Already_a_User_Login_now {
            get {
                return ResourceManager.GetString("Label_Already_a_User_Login_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        internal static string Label_Articles {
            get {
                return ResourceManager.GetString("Label_Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask Me.
        /// </summary>
        internal static string Label_Askme {
            get {
                return ResourceManager.GetString("Label_Askme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block User.
        /// </summary>
        internal static string Label_Block {
            get {
                return ResourceManager.GetString("Label_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        internal static string Label_Blocked {
            get {
                return ResourceManager.GetString("Label_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Blocked Users.
        /// </summary>
        internal static string Label_Blocked_List_Empty {
            get {
                return ResourceManager.GetString("Label_Blocked_List_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked users.
        /// </summary>
        internal static string Label_Blocked_Users {
            get {
                return ResourceManager.GetString("Label_Blocked_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Label_Blue {
            get {
                return ResourceManager.GetString("Label_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Label_Cancel {
            get {
                return ResourceManager.GetString("Label_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Download.
        /// </summary>
        internal static string Label_CannotDownload {
            get {
                return ResourceManager.GetString("Label_CannotDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Send.
        /// </summary>
        internal static string Label_CannotSend {
            get {
                return ResourceManager.GetString("Label_CannotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Upload.
        /// </summary>
        internal static string Label_CannotUpload {
            get {
                return ResourceManager.GetString("Label_CannotUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chats.
        /// </summary>
        internal static string Label_Chats {
            get {
                return ResourceManager.GetString("Label_Chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection.
        /// </summary>
        internal static string Label_CheckYourInternetConnection {
            get {
                return ResourceManager.GetString("Label_CheckYourInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose from Galery.
        /// </summary>
        internal static string Label_Choose_from_Galery {
            get {
                return ResourceManager.GetString("Label_Choose_from_Galery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your Led Color.
        /// </summary>
        internal static string Label_Choose_Your_Led_Color {
            get {
                return ResourceManager.GetString("Label_Choose_Your_Led_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Lost.
        /// </summary>
        internal static string Label_Connection_Lost {
            get {
                return ResourceManager.GetString("Label_Connection_Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Label_Contact {
            get {
                return ResourceManager.GetString("Label_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        internal static string Label_Contact_Number {
            get {
                return ResourceManager.GetString("Label_Contact_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Label_Contacts {
            get {
                return ResourceManager.GetString("Label_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string Label_CurrentPassword {
            get {
                return ResourceManager.GetString("Label_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Label_Default {
            get {
                return ResourceManager.GetString("Label_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Label_Delete {
            get {
                return ResourceManager.GetString("Label_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        internal static string Label_Desktop {
            get {
                return ResourceManager.GetString("Label_Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont agree.
        /// </summary>
        internal static string Label_Dot_Agree {
            get {
                return ResourceManager.GetString("Label_Dot_Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        internal static string Label_Downloading {
            get {
                return ResourceManager.GetString("Label_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Sound.
        /// </summary>
        internal static string Label_DownloadSound {
            get {
                return ResourceManager.GetString("Label_DownloadSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Video.
        /// </summary>
        internal static string Label_DownloadVideo {
            get {
                return ResourceManager.GetString("Label_DownloadVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT PROFILE.
        /// </summary>
        internal static string Label_Edit_Profile {
            get {
                return ResourceManager.GetString("Label_Edit_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing Post.
        /// </summary>
        internal static string Label_Editing_Post {
            get {
                return ResourceManager.GetString("Label_Editing_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Has Been Send.
        /// </summary>
        internal static string Label_Email_Has_Been_Send {
            get {
                return ResourceManager.GetString("Label_Email_Has_Been_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string Label_Empty {
            get {
                return ResourceManager.GetString("Label_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No any chat activty.
        /// </summary>
        internal static string Label_Empty_ChatActivity {
            get {
                return ResourceManager.GetString("Label_Empty_ChatActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No any contact.
        /// </summary>
        internal static string Label_Empty_Contacts {
            get {
                return ResourceManager.GetString("Label_Empty_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Search.
        /// </summary>
        internal static string Label_Empty_Search {
            get {
                return ResourceManager.GetString("Label_Empty_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Label_Error {
            get {
                return ResourceManager.GetString("Label_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone.
        /// </summary>
        internal static string Label_Everyone {
            get {
                return ResourceManager.GetString("Label_Everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Label_Female {
            get {
                return ResourceManager.GetString("Label_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish!.
        /// </summary>
        internal static string Label_Finish {
            get {
                return ResourceManager.GetString("Label_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string Label_First_Name {
            get {
                return ResourceManager.GetString("Label_First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        internal static string Label_Follow {
            get {
                return ResourceManager.GetString("Label_Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow All / Next.
        /// </summary>
        internal static string Label_Follow_All_And_Next {
            get {
                return ResourceManager.GetString("Label_Follow_All_And_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Requests.
        /// </summary>
        internal static string Label_Follow_Requests {
            get {
                return ResourceManager.GetString("Label_Follow_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        internal static string Label_Following {
            get {
                return ResourceManager.GetString("Label_Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget my password.
        /// </summary>
        internal static string Label_Forget_My_Password {
            get {
                return ResourceManager.GetString("Label_Forget_My_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string Label_Forgot_your_password {
            get {
                return ResourceManager.GetString("Label_Forgot_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t worry type your email here and we will recover it for you..
        /// </summary>
        internal static string Label_Forgot_your_password_DontWorry {
            get {
                return ResourceManager.GetString("Label_Forgot_your_password_DontWorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend List.
        /// </summary>
        internal static string Label_Friend_List {
            get {
                return ResourceManager.GetString("Label_Friend_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Requests.
        /// </summary>
        internal static string Label_Friend_Requests {
            get {
                return ResourceManager.GetString("Label_Friend_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        internal static string Label_Friends {
            get {
                return ResourceManager.GetString("Label_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Label_Gender {
            get {
                return ResourceManager.GetString("Label_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string Label_General_Settings {
            get {
                return ResourceManager.GetString("Label_General_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Label_Green {
            get {
                return ResourceManager.GetString("Label_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Label_Help {
            get {
                return ResourceManager.GetString("Label_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey there i am using.
        /// </summary>
        internal static string Label_Hey_There {
            get {
                return ResourceManager.GetString("Label_Hey_There", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image File.
        /// </summary>
        internal static string Label_Image_File {
            get {
                return ResourceManager.GetString("Label_Image_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Friends .
        /// </summary>
        internal static string Label_invite {
            get {
                return ResourceManager.GetString("Label_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi Lets talk on .
        /// </summary>
        internal static string Label_invite_sms_text {
            get {
                return ResourceManager.GetString("Label_invite_sms_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Label_Last_Name {
            get {
                return ResourceManager.GetString("Label_Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen.
        /// </summary>
        internal static string Label_LastSeen {
            get {
                return ResourceManager.GetString("Label_LastSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Led Color.
        /// </summary>
        internal static string Label_Led_Color {
            get {
                return ResourceManager.GetString("Label_Led_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        internal static string Label_Like {
            get {
                return ResourceManager.GetString("Label_Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liked.
        /// </summary>
        internal static string Label_Liked {
            get {
                return ResourceManager.GetString("Label_Liked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link...
        /// </summary>
        internal static string Label_Link {
            get {
                return ResourceManager.GetString("Label_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening To.
        /// </summary>
        internal static string Label_Listening_To {
            get {
                return ResourceManager.GetString("Label_Listening_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load More Products.
        /// </summary>
        internal static string Label_Load_More_Products {
            get {
                return ResourceManager.GetString("Label_Load_More_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Label_Loading {
            get {
                return ResourceManager.GetString("Label_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading messages from server ....
        /// </summary>
        internal static string Label_Loading_Messages_from_server {
            get {
                return ResourceManager.GetString("Label_Loading_Messages_from_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading User Contacts.
        /// </summary>
        internal static string Label_Loading_User_Contacts {
            get {
                return ResourceManager.GetString("Label_Loading_User_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading User Data.
        /// </summary>
        internal static string Label_Loading_User_Data {
            get {
                return ResourceManager.GetString("Label_Loading_User_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Label_Location {
            get {
                return ResourceManager.GetString("Label_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging out.
        /// </summary>
        internal static string Label_Logging_out {
            get {
                return ResourceManager.GetString("Label_Logging_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Label_Login {
            get {
                return ResourceManager.GetString("Label_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with.
        /// </summary>
        internal static string Label_Login_with {
            get {
                return ResourceManager.GetString("Label_Login_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Label_Logout {
            get {
                return ResourceManager.GetString("Label_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenta.
        /// </summary>
        internal static string Label_Magenta {
            get {
                return ResourceManager.GetString("Label_Magenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Label_Male {
            get {
                return ResourceManager.GetString("Label_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maroon.
        /// </summary>
        internal static string Label_Maroon {
            get {
                return ResourceManager.GetString("Label_Maroon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentions.
        /// </summary>
        internal static string Label_Mentions {
            get {
                return ResourceManager.GetString("Label_Mentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string Label_Messages {
            get {
                return ResourceManager.GetString("Label_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Label_Mobile {
            get {
                return ResourceManager.GetString("Label_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Friends.
        /// </summary>
        internal static string Label_My_Friends {
            get {
                return ResourceManager.GetString("Label_My_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Photos.
        /// </summary>
        internal static string Label_My_Photos {
            get {
                return ResourceManager.GetString("Label_My_Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string Label_My_Profile {
            get {
                return ResourceManager.GetString("Label_My_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string Label_NewPassword {
            get {
                return ResourceManager.GetString("Label_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Label_Next {
            get {
                return ResourceManager.GetString("Label_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string Label_NO {
            get {
                return ResourceManager.GetString("Label_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No any chat activity available.
        /// </summary>
        internal static string Label_NoAnyChatActivityAvailable {
            get {
                return ResourceManager.GetString("Label_NoAnyChatActivityAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Settings.
        /// </summary>
        internal static string Label_Notification_Settings {
            get {
                return ResourceManager.GetString("Label_Notification_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Label_Notifications {
            get {
                return ResourceManager.GetString("Label_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string Label_Offline {
            get {
                return ResourceManager.GetString("Label_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Mode.
        /// </summary>
        internal static string Label_Offline_Mode {
            get {
                return ResourceManager.GetString("Label_Offline_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Label_OK {
            get {
                return ResourceManager.GetString("Label_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once You start a new Conversation You&apos;ll see it here.
        /// </summary>
        internal static string Label_Once_You_start_new_Conversation {
            get {
                return ResourceManager.GetString("Label_Once_You_start_new_Conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string Label_Online {
            get {
                return ResourceManager.GetString("Label_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only me.
        /// </summary>
        internal static string Label_Only_me {
            get {
                return ResourceManager.GetString("Label_Only_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string Label_Orange {
            get {
                return ResourceManager.GetString("Label_Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Settings.
        /// </summary>
        internal static string Label_Password_Settings {
            get {
                return ResourceManager.GetString("Label_Password_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People Follow Me.
        /// </summary>
        internal static string Label_People_Follow_Me {
            get {
                return ResourceManager.GetString("Label_People_Follow_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People I Follow.
        /// </summary>
        internal static string Label_People_I_Follow {
            get {
                return ResourceManager.GetString("Label_People_I_Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Label_Phone {
            get {
                return ResourceManager.GetString("Label_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        internal static string Label_Photo {
            get {
                return ResourceManager.GetString("Label_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing....
        /// </summary>
        internal static string Label_Playing {
            get {
                return ResourceManager.GetString("Label_Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid e-mail.
        /// </summary>
        internal static string Label_Please_Enter_Valid_Email {
            get {
                return ResourceManager.GetString("Label_Please_Enter_Valid_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        internal static string Label_Please_Wait {
            get {
                return ResourceManager.GetString("Label_Please_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your contact name.
        /// </summary>
        internal static string Label_Please_write_your_contact_name {
            get {
                return ResourceManager.GetString("Label_Please_write_your_contact_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Write your full email address.
        /// </summary>
        internal static string Label_Please_Write_your_full_email {
            get {
                return ResourceManager.GetString("Label_Please_Write_your_full_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Notification.
        /// </summary>
        internal static string Label_Popup_Notification {
            get {
                return ResourceManager.GetString("Label_Popup_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting.
        /// </summary>
        internal static string Label_Posting {
            get {
                return ResourceManager.GetString("Label_Posting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Label_Price {
            get {
                return ResourceManager.GetString("Label_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string Label_Privacy {
            get {
                return ResourceManager.GetString("Label_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Settings.
        /// </summary>
        internal static string Label_Privacy_Settings {
            get {
                return ResourceManager.GetString("Label_Privacy_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture.
        /// </summary>
        internal static string Label_Profile_Picture {
            get {
                return ResourceManager.GetString("Label_Profile_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        internal static string Label_Purple {
            get {
                return ResourceManager.GetString("Label_Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Label_Question {
            get {
                return ResourceManager.GetString("Label_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Users.
        /// </summary>
        internal static string Label_Recommended_Users {
            get {
                return ResourceManager.GetString("Label_Recommended_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording....
        /// </summary>
        internal static string Label_Recording {
            get {
                return ResourceManager.GetString("Label_Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start recording by pressing on button.
        /// </summary>
        internal static string Label_Recourd_Start {
            get {
                return ResourceManager.GetString("Label_Recourd_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recourd Video.
        /// </summary>
        internal static string Label_Recourd_Video {
            get {
                return ResourceManager.GetString("Label_Recourd_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Label_Red {
            get {
                return ResourceManager.GetString("Label_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Label_Refresh {
            get {
                return ResourceManager.GetString("Label_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Contacts.
        /// </summary>
        internal static string Label_Refresh_Contacts {
            get {
                return ResourceManager.GetString("Label_Refresh_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register New Account.
        /// </summary>
        internal static string Label_Register_New_Account {
            get {
                return ResourceManager.GetString("Label_Register_New_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now and start chating with your friends..
        /// </summary>
        internal static string Label_Register_Now_And {
            get {
                return ResourceManager.GetString("Label_Register_Now_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        internal static string Label_RepeatPassword {
            get {
                return ResourceManager.GetString("Label_RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a problem.
        /// </summary>
        internal static string Label_Report_TO_us {
            get {
                return ResourceManager.GetString("Label_Report_TO_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request removed.
        /// </summary>
        internal static string Label_Request_removed {
            get {
                return ResourceManager.GetString("Label_Request_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested.
        /// </summary>
        internal static string Label_Requested {
            get {
                return ResourceManager.GetString("Label_Requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Label_Retry {
            get {
                return ResourceManager.GetString("Label_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Label_Save {
            get {
                return ResourceManager.GetString("Label_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string Label_Saved {
            get {
                return ResourceManager.GetString("Label_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Label_Search {
            get {
                return ResourceManager.GetString("Label_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Contacts.
        /// </summary>
        internal static string Label_Search_Contacts {
            get {
                return ResourceManager.GetString("Label_Search_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Filter.
        /// </summary>
        internal static string Label_Search_Filter {
            get {
                return ResourceManager.GetString("Label_Search_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Random.
        /// </summary>
        internal static string Label_Search_Random {
            get {
                return ResourceManager.GetString("Label_Search_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Box Filter.
        /// </summary>
        internal static string Label_SearchBoxFilter {
            get {
                return ResourceManager.GetString("Label_SearchBoxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender :.
        /// </summary>
        internal static string Label_SearchByGender {
            get {
                return ResourceManager.GetString("Label_SearchByGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Settings.
        /// </summary>
        internal static string Label_SearchSettings {
            get {
                return ResourceManager.GetString("Label_SearchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string Label_Security {
            get {
                return ResourceManager.GetString("Label_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a contact.
        /// </summary>
        internal static string Label_Select_a_contact {
            get {
                return ResourceManager.GetString("Label_Select_a_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Privacy.
        /// </summary>
        internal static string Label_Select_Privacy {
            get {
                return ResourceManager.GetString("Label_Select_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Label_Send {
            get {
                return ResourceManager.GetString("Label_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS to ?.
        /// </summary>
        internal static string Label_Send_SMS_TO {
            get {
                return ResourceManager.GetString("Label_Send_SMS_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Label_Settings {
            get {
                return ResourceManager.GetString("Label_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show your unique personality and style..
        /// </summary>
        internal static string Label_Show_your_unique {
            get {
                return ResourceManager.GetString("Label_Show_your_unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up!.
        /// </summary>
        internal static string Label_Sign_Up {
            get {
                return ResourceManager.GetString("Label_Sign_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        internal static string Label_Silver {
            get {
                return ResourceManager.GetString("Label_Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        internal static string Label_Sound {
            get {
                return ResourceManager.GetString("Label_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound File.
        /// </summary>
        internal static string Label_Sound_File {
            get {
                return ResourceManager.GetString("Label_Sound_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound File.
        /// </summary>
        internal static string Label_SoundFile {
            get {
                return ResourceManager.GetString("Label_SoundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Label_SoundPause {
            get {
                return ResourceManager.GetString("Label_SoundPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Record.
        /// </summary>
        internal static string Label_SoundRecord {
            get {
                return ResourceManager.GetString("Label_SoundRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Adding New Contacts ?.
        /// </summary>
        internal static string Label_Start_Adding_New_Contacts {
            get {
                return ResourceManager.GetString("Label_Start_Adding_New_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new conversations by going to &gt; Contacts.
        /// </summary>
        internal static string Label_Start_New_Conv {
            get {
                return ResourceManager.GetString("Label_Start_New_Conv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start seaching by typing on search box.
        /// </summary>
        internal static string Label_Start_Seaching {
            get {
                return ResourceManager.GetString("Label_Start_Seaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status :.
        /// </summary>
        internal static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticker.
        /// </summary>
        internal static string Label_Sticker {
            get {
                return ResourceManager.GetString("Label_Sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stickers.
        /// </summary>
        internal static string Label_Stickers {
            get {
                return ResourceManager.GetString("Label_Stickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Phone Contacts.
        /// </summary>
        internal static string Label_Sync_Phone_Contacts {
            get {
                return ResourceManager.GetString("Label_Sync_Phone_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a Picture.
        /// </summary>
        internal static string Label_Take_a_Picture {
            get {
                return ResourceManager.GetString("Label_Take_a_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        internal static string Label_Terms {
            get {
                return ResourceManager.GetString("Label_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By accessing this messenger, you are agreeing to be bound by these Messenger, Terms and Conditions of Use, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site. The materials contained in this web site are protected by applicable copyright and trade mark law..
        /// </summary>
        internal static string Label_Terms_LongText {
            get {
                return ResourceManager.GetString("Label_Terms_LongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do not agree with any of these terms, you are prohibited from using or accessing this App..
        /// </summary>
        internal static string Label_Terms_notAccepted {
            get {
                return ResourceManager.GetString("Label_Terms_notAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        internal static string Label_Try_Again {
            get {
                return ResourceManager.GetString("Label_Try_Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typping....
        /// </summary>
        internal static string Label_Typping {
            get {
                return ResourceManager.GetString("Label_Typping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        internal static string Label_Unavailable {
            get {
                return ResourceManager.GetString("Label_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Avatar.
        /// </summary>
        internal static string Label_Upload_Avatar {
            get {
                return ResourceManager.GetString("Label_Upload_Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Cover.
        /// </summary>
        internal static string Label_Upload_Cover {
            get {
                return ResourceManager.GetString("Label_Upload_Cover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        internal static string Label_Uploading {
            get {
                return ResourceManager.GetString("Label_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Social Logins.
        /// </summary>
        internal static string Label_Use_Social_Logins {
            get {
                return ResourceManager.GetString("Label_Use_Social_Logins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your credentials to login..
        /// </summary>
        internal static string Label_Use_your_credentials_to_login {
            get {
                return ResourceManager.GetString("Label_Use_your_credentials_to_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Contacts Loaded.
        /// </summary>
        internal static string Label_User_Contacts_Loaded {
            get {
                return ResourceManager.GetString("Label_User_Contacts_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Data Loaded.
        /// </summary>
        internal static string Label_User_Data_Loaded {
            get {
                return ResourceManager.GetString("Label_User_Data_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Search Settings.
        /// </summary>
        internal static string Label_User_Search_Settings {
            get {
                return ResourceManager.GetString("Label_User_Search_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Label_Username {
            get {
                return ResourceManager.GetString("Label_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Label_Users {
            get {
                return ResourceManager.GetString("Label_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrate.
        /// </summary>
        internal static string Label_Vibrate {
            get {
                return ResourceManager.GetString("Label_Vibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string Label_Video {
            get {
                return ResourceManager.GetString("Label_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video File.
        /// </summary>
        internal static string Label_Video_File {
            get {
                return ResourceManager.GetString("Label_Video_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video File.
        /// </summary>
        internal static string Label_VideoFile {
            get {
                return ResourceManager.GetString("Label_VideoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Full Profile.
        /// </summary>
        internal static string Label_View_Full_Profile {
            get {
                return ResourceManager.GetString("Label_View_Full_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        internal static string Label_Web {
            get {
                return ResourceManager.GetString("Label_Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now chat is faster, easier, and more fun..
        /// </summary>
        internal static string Label_Welcome_page_Header {
            get {
                return ResourceManager.GetString("Label_Welcome_page_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay connected to friends and families in today’s fast paced and ever changing worlds..
        /// </summary>
        internal static string Label_Welcome_Page_Sub_Header {
            get {
                return ResourceManager.GetString("Label_Welcome_Page_Sub_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to .
        /// </summary>
        internal static string Label_Welcome_to_App {
            get {
                return ResourceManager.GetString("Label_Welcome_to_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who can add me?.
        /// </summary>
        internal static string Label_WhoCan_Add_me {
            get {
                return ResourceManager.GetString("Label_WhoCan_Add_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who can follow me?.
        /// </summary>
        internal static string Label_WhoCan_Follow_me {
            get {
                return ResourceManager.GetString("Label_WhoCan_Follow_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who can message me?.
        /// </summary>
        internal static string Label_WhoCan_Message_me {
            get {
                return ResourceManager.GetString("Label_WhoCan_Message_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who can see my birthday?.
        /// </summary>
        internal static string Label_WhoCan_See_my_Birthday {
            get {
                return ResourceManager.GetString("Label_WhoCan_See_my_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save your password ?.
        /// </summary>
        internal static string Label_WouldYouLikeToSaveYourPassword {
            get {
                return ResourceManager.GetString("Label_WouldYouLikeToSaveYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would You Like To Send Your Sound.
        /// </summary>
        internal static string Label_WouldYouLikeToSendYourSound {
            get {
                return ResourceManager.GetString("Label_WouldYouLikeToSendYourSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string Label_Yellow {
            get {
                return ResourceManager.GetString("Label_Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Label_Yes {
            get {
                return ResourceManager.GetString("Label_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are still Offline.
        /// </summary>
        internal static string Label_You_are_still_Offline {
            get {
                return ResourceManager.GetString("Label_You_are_still_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Cannot Pick an Image.
        /// </summary>
        internal static string Label_YouCannotPickAnImage {
            get {
                return ResourceManager.GetString("Label_YouCannotPickAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password dont match..
        /// </summary>
        internal static string Label_Your_Password_Dont_Match {
            get {
                return ResourceManager.GetString("Label_Your_Password_Dont_Match", resourceCulture);
            }
        }
    }
}
